/**
 * This file was auto-generated by the program based on the back-end data structure.
 * Do not make direct changes to the file.
 */

import {
  Encoding,
  HeaderAndContent,
  OnlyContent,
  OnlyHeader
} from './data-schema';

export interface BusinessGetEP {
  Responses: {
    /**
     * @Description success
     */
    200: {
      Content: null;
      Headers: {
        /**
         * @Description cache-control
         */
        'cache-control'?: string;
        /**
         * @Description date time
         *
         * @Format Date
         *
         * @SerializeFormat application/json
         */
        date: string;
        encoding?: Encoding;
      };
    };
    201: OnlyHeader;
    202: OnlyContent;
    203: HeaderAndContent;
    /**
     * @Description not found
     */
    404: {
      Content: null;
    };
  };
}
