/**
 * This file was auto-generated by the program based on the back-end data structure.
 * Do not make direct changes to the file.
 */

export type Encoding = number;

/**
 * @Description have header and content
 */
export interface HeaderAndContent {
  Content: {
    'application/json': string;
    'application/octet-stream': number;
  };
  Headers: {
    'content-type'?: string;
  };
}

/**
 * @Description only have content
 */
export interface OnlyContent {
  Content: {
    'application/octet-stream': {
      readonly age?: number;
      readonly name?: string;
    };
  };
}

/**
 * @Description only have header
 */
export interface OnlyHeader {
  Content: null;
  Headers: {
    cookie?: string;
  };
}
