/**
 * This file was auto-generated by the program based on the back-end data structure.
 * Do not make direct changes to the file.
 */

import { Cat, Dog } from './data-schema';
import { AnyOf, OneOf } from './Helper';

export interface BusinessGetEP {
  Responses: {
    /**
     * @Description success
     */
    200: {
      Content: {
        'application/json': {
          readonly allOf?: Cat & Dog;
          readonly anyOf?: AnyOf<[Dog, Cat]>;
          readonly mix?: OneOf<[AnyOf<[{
            readonly name?: string;
          }, {
            readonly age?: number;
          }, {
            readonly city?: string;
            readonly salary?: number | null;
          }]>, Cat]>;
          readonly oneOf?: OneOf<[Dog, Cat]>;
        };
      };
    };
  };
}
