/**
 * This file was auto-generated by the program based on the back-end data structrue.
 * Do not make direct changes to the file.
 */

import { Cat, Dog } from './data-schema';
import { AnyOf, OneOf } from './helper';

export interface BusinessGetEP {
  Responses: {
    /**
     * @Description success
     */
    200: {
      Content: {
        'application/json': {
          readonly allOf?: Dog & Cat;
          readonly anyOf?: AnyOf<[Dog, Cat]>;
          /**
           * @Description name
           *
           * @Description age
           *
           * @Description city
           *
           * @Description salary
           */
          readonly mix?: OneOf<[AnyOf<[{
            readonly name?: string;
          }, {
            readonly age?: number;
          }, {
            readonly city?: string;
          } & {
            readonly salary?: number | null;
          }]>, Cat]>;
          readonly oneOf?: OneOf<[Dog, Cat]>;
        };
      };
    };
  };
}
