/**
 * This file was auto-generated by the program based on the back-end data structrue.
 * Do not make direct changes to the file.
 */

import { AnyOf, OneOf } from './helper';

export interface BusinessGetEP {
  Responses: {
    /**
     * @Description success
     */
    200: {
      Content: {
        'application/json': {
          readonly allOf?: Dog & Cat;
          readonly anyOf?: AnyOf<[Dog, Cat]>;
          /**
           * @Description name
           *
           * @Description age
           *
           * @Description city
           *
           * @Description salary
           */
          readonly mix?: OneOf<[AnyOf<[{
            readonly name?: string;
          }, {
            readonly age: number;
          }, {
            readonly city?: string;
          } & {
            readonly salary?: number | null;
          }]>, Cat]>;
          readonly oneOf?: OneOf<[Dog, Cat]>;
        };
      };
    };
  };
}

export interface Cat {
  readonly catch?: boolean;
  readonly climb: boolean;
}

export interface Dog {
  readonly bark: string;
  readonly color?: 'red' | 'green' | null;
  /**
   * @Format date-time
   */
  readonly 'date-time'?: string;
  /**
   * @Format date-time
   */
  readonly 'date-timeNull'?: string | null;
  readonly size?: 'Big' | 'small';
  /**
   * @Format uuid
   */
  readonly uid?: string;
  /**
   * @Format uuid
   */
  readonly uidNull?: string | null;
}
