/**
 * This file was auto-generated by the program based on the back-end data structrue.
 * Do not make direct changes to the file.
 */

import { AnyOf, OneOf } from './common/helper';
import { BusinessGetEP } from './Operations/business';

/**
 * @OpenApi 3.0.1
 *
 * @Title Swagger To Ts
 *
 * @Version V1
 */
export interface Routes {
  '/business': {
    GET: BusinessGetEP;
  };
}
