/**
 * This file was auto-generated by the program based on the back-end data structrue.
 * Do not make direct changes to the file.
 */

export interface BusinessGetEP {
  Responses: {
    /**
     * @Description success
     */
    200: {
      Content: null;
      Headers: {
        /**
         * @Description cache-control
         */
        'cache-control'?: string;
        /**
         * @Description date time
         *
         * @Deprecated False
         *
         * @AllowEmptyValue False
         *
         * @SerializeFormat application/json
         *
         * @Format Date
         */
        date: string;
        encoding?: Encoding;
      };
    };
    201: OnlyHeader;
    202: OnlyContent;
    203: HeaderAndContent;
    /**
     * @Description not found
     */
    404: {
      Content: null;
    };
  };
}

export type Encoding = number;

/**
 * @Description have header and content
 */
export interface HeaderAndContent {
  Content: {
    'application/json': string;
    'application/octet-stream': number;
  };
  Headers: {
    'content-type'?: string;
  };
}

/**
 * @Description only have content
 */
export interface OnlyContent {
  Content: {
    'application/octet-stream': {
      readonly age?: number;
      readonly name?: string;
    };
  };
}

/**
 * @Description only have header
 */
export interface OnlyHeader {
  Content: null;
  Headers: {
    cookie?: string;
  };
}
