/**
 * This file was auto-generated by the program based on the back-end data structrue.
 * Do not make direct changes to the file.
 */

export interface BusinessGetEP {
  Responses: {
    /**
     * @Description success
     */
    200: {
      Content: {
        'application/json': {
          readonly Info?: {
            readonly EnumArrayItems?: readonly ('hello' | 'world' | null)[][];
            readonly enums?: 1 | '2' | 4444444444.2344 | null;
            readonly ObjectArrayItems?: readonly Profile[];
            readonly profile?: Profile;
            readonly RecordArrayItems?: RecordArray;
            readonly recordObject?: Record<string, unknown> | null;
            readonly unknown?: unknown;
            readonly UnknownArrayItems?: readonly (unknown[] | null)[];
          };
        };
      };
    };
  };
}

export interface Profile {
  readonly cities?: 'beijing' | 'shanghai' | null;
}

export type RecordArray = ((Record<string, unknown> | null)[] | null)[];
