/**
 * This file was auto-generated by the program based on the back-end data structrue.
 * Do not make direct changes to the file.
 */

export interface BusinessDeleteEP {
  Responses: {
    /**
     * @Description delete success
     */
    200: {
      Content: null;
    };
  };
}

export interface BusinessGetEP {
  Responses: {
    /**
     * @Description get success
     */
    200: {
      Content: null;
    };
  };
}

export interface BusinessHeadEP {
  Responses: {
    /**
     * @Description head success
     */
    200: {
      Content: null;
    };
  };
}

export interface BusinessOptionsEP {
  Responses: {
    /**
     * @Description options success
     */
    200: {
      Content: null;
    };
  };
}

export interface BusinessPatchEP {
  Responses: {
    /**
     * @Description patch success
     */
    200: {
      Content: null;
    };
  };
}

export interface BusinessPostEP {
  Responses: {
    /**
     * @Description post success
     */
    200: {
      Content: null;
    };
  };
}

export interface BusinessPutEP {
  Responses: {
    /**
     * @Description put success
     */
    200: {
      Content: null;
    };
  };
}

export interface OperationIdEP {
  Responses: {
    /**
     * @Description trace success
     */
    200: {
      Content: null;
    };
  };
}
