/**
 * This file was auto-generated by the program based on the back-end data structure.
 * Do not make direct changes to the file.
 */

export interface BusinessGetEP {
  Request: {
    Query: BusinessGetQuery;
  };
  Responses: {
    /**
     * @Description get success
     */
    200: {
      Content: null;
    };
  };
}

export interface BusinessGetQuery {
  readonly id?: number;
  readonly name?: string;
}
