/**
 * This file was auto-generated by the program based on the back-end data structrue.
 * Do not make direct changes to the file.
 */

export interface BusinessGetEP {
  Request: {
    Query: BusinessGetQuery;
  };
  Responses: {
    /**
     * @Description not found
     */
    200: {
      Content: null;
    };
  };
}

export interface BusinessGetQuery extends Date, Id, Name {
  /**
   * @Description permission
   */
  readonly permission?: string;
}

export interface Date {
  readonly date?: string;
}

/**
 * @Description ID
 */
export interface Id {
  readonly id: number;
}

export interface Name {
  readonly name?: string;
}
