/**
 * This file was auto-generated by the program based on the back-end data structure.
 * Do not make direct changes to the file.
 */

export interface Date {
  readonly date?: string;
}

/**
 * @Description ID
 */
export interface Id {
  readonly id: number;
}

export interface Name {
  readonly name?: string;
}
