/**
 * This file was auto-generated by the program based on the back-end data structrue.
 * Do not make direct changes to the file.
 */

export enum City {
  Beijing = 'Beijing',
  Shanghai = 'Shanghai'
}

export enum Color {
  red = 'red',
  green = 'green'
}
