/**
 * This file was auto-generated by the program based on the back-end data structure.
 * Do not make direct changes to the file.
 */

import { UsedByRequestAndResponse, UsedByResponse } from './data-schema';

export interface BusinessGetEP {
  Responses: {
    /**
     * @Description success
     */
    200: {
      Content: {
        'application/json': UsedByRequestAndResponse;
      };
    };
  };
}

export interface BusinessPostEP {
  Request: {
    Query?: BusinessPostQuery;
  };
  Responses: {
    /**
     * @Description success
     */
    200: {
      Content: {
        'application/json': {
          readonly inline: {
            readonly age?: number | null;
            readonly name: string;
            readonly usedInResponseAndRequestInline?: UsedByRequestAndResponse;
            readonly usedInResponseInline: UsedByResponse;
          };
          readonly usedInResponse: UsedByResponse;
          readonly usedInResponseAndRequest?: UsedByRequestAndResponse;
        };
      };
    };
  };
}

export interface BusinessPostQuery {
  readonly req?: UsedByRequestAndResponse;
}
