/**
 * This file was auto-generated by the program based on the back-end data structure.
 * Do not make direct changes to the file.
 */

export interface UsedByRequestAndResponse {
  readonly age?: number | null;
  readonly name?: string;
}

export interface UsedByResponse {
  readonly age?: number | null;
  readonly name: string;
}
