/**
 * This file was auto-generated by the program based on the back-end data structrue.
 * Do not make direct changes to the file.
 */

import { NonNullAsRequired } from './helper';

export interface BusinessGetEP {
  Responses: {
    /**
     * @Description not found
     */
    200: {
      Content: {
        'application/json': BusinessGet200JsonResponse;
      };
    };
  };
}

export interface BusinessGet200Json {
  readonly int?: number;
  readonly object?: Age;
  readonly string?: string;
}

export type BusinessGet200JsonResponse = NonNullAsRequired<BusinessGet200Json>;

export interface Age {
  readonly name?: string;
}
