/**
 * This file was auto-generated by the program based on the back-end data structrue.
 * Do not make direct changes to the file.
 */

export interface BusinessGetEP {
  Request: {
    Query: BusinessGetQuery;
  };
  Responses: {
    /**
     * @Description success
     */
    200: {
      Content: null;
    };
  };
}

export interface BusinessGetQuery {
  readonly versionInfo?: {
    /**
     * @Format date-time
     */
    readonly 'date-From': string;
    /**
     * @Format date-time
     */
    readonly 'date-FromNull'?: string;
    readonly id: number;
    readonly idWithNull?: number;
    readonly isActive: boolean;
    readonly isActiveNull?: boolean;
    /**
     * @Format uuid
     */
    readonly uid: string;
    /**
     * @Format uuid
     */
    readonly uidNull?: string;
  };
}
