/**
 * This file was auto-generated by the program based on the back-end data structrue.
 * Do not make direct changes to the file.
 */

import {
  BusinessDeleteEP,
  BusinessGetEP,
  BusinessHeadEP,
  BusinessOptionsEP,
  BusinessPatchEP,
  BusinessPostEP,
  BusinessPutEP,
  OperationIdEP
} from './Operations/business';

/**
 * @OpenApi 3.0.1
 *
 * @Title Swagger To Ts
 *
 * @Version V1
 */
export interface Routes {
  '/api/business/user': {
    DELETE: BusinessDeleteEP;
    GET: BusinessGetEP;
    HEAD: BusinessHeadEP;
    OPTIONS: BusinessOptionsEP;
    PATCH: BusinessPatchEP;
    POST: BusinessPostEP;
    PUT: BusinessPutEP;
    TRACE: OperationIdEP;
  };
}
