/**
 * This file was auto-generated by the program based on the back-end data structrue.
 * Do not make direct changes to the file.
 */

export interface BusinessGetEP {
  Responses: {
    /**
     * @Description get success
     */
    200: {
      Content: null;
    };
  };
}

export interface BusinessGetEP1 {
  Responses: {
    /**
     * @Description get success
     */
    404: {
      Content: null;
    };
  };
}

export interface BusinessGetEP2 {
  Responses: {
    /**
     * @Description get success
     */
    404: {
      Content: null;
    };
  };
}
