/**
 * This file was auto-generated by the program based on the back-end data structure.
 * Do not make direct changes to the file.
 */

export interface BusinessGetEP {
  Request: {
    /**
     * @Description request body
     */
    Body?: {
      'application/json': string;
    };
  };
  Responses: {
    /**
     * @Description not found
     */
    200: {
      Content: null;
    };
  };
}
