/**
 * This file was auto-generated by the program based on the back-end data structrue.
 * Do not make direct changes to the file.
 */

import { NonNullAsRequired } from './helper';

export interface BusinessGetEP {
  Responses: {
    /**
     * @Description success
     */
    200: {
      Content: {
        'application/json': BusinessGet200ApplicationJsonResponse;
      };
    };
  };
}

export interface BusinessGet200ApplicationJson {
  readonly info?: {
    readonly enumArrayItems?: readonly ('hello' | 'world' | null)[][];
    readonly enums?: 1 | '2' | 4444444444.2344 | null;
    readonly objectArrayItems?: readonly Profile[];
    readonly profile?: Profile;
    readonly recordArrayItems?: RecordArray;
    readonly recordObject?: Record<string, unknown> | null;
    readonly unknown?: unknown;
    readonly unknownArrayItems?: readonly (unknown[] | null)[];
  };
}

export type BusinessGet200ApplicationJsonResponse =
  NonNullAsRequired<BusinessGet200ApplicationJson>;

export interface Profile {
  readonly cities?: 'beijing' | 'shanghai' | null;
}

export type RecordArray = ((Record<string, unknown> | null)[] | null)[];
