/**
 * This file was auto-generated by the program based on the back-end data structrue.
 * Do not make direct changes to the file.
 */

export interface Profile {
  readonly cities?: 'beijing' | 'shanghai' | null;
}

export type RecordArray = ((Record<string, unknown> | null)[] | null)[];
