/**
 * This file was auto-generated by the program based on the back-end data structure.
 * Do not make direct changes to the file.
 */

export interface AgenciesGetEP {
  Responses: {
    /**
     * @Description success
     */
    200: {
      Content: null;
    };
  };
}
