/**
 * This file was auto-generated by the program based on the back-end data structure.
 * Do not make direct changes to the file.
 */

import {
  Cat,
  Dog,
  ExtendOne,
  ExtendTwo,
  ExtendTwoAndProperties
} from './data-schema';

export interface BusinessGetEP {
  Responses: {
    /**
     * @Description success
     */
    200: {
      Content: {
        'application/json': {
          readonly extends?: ExtendTwoAndProperties;
          readonly inline?: Dog & Cat;
          readonly inlineWithProperty?: Dog & Cat & {
            /**
             * @Format money
             */
            readonly prices?: number;
          };
          readonly one?: ExtendOne;
          readonly two?: ExtendTwo;
        };
      };
    };
  };
}
