/**
 * This file was auto-generated by the program based on the back-end data structure.
 * Do not make direct changes to the file.
 */

export interface Cat {
  readonly catch?: boolean;
  readonly climb: boolean;
}

export interface Dog {
  /**
   * @Format date-time
   */
  readonly 'date-time'?: string;
  /**
   * @Format date-time
   */
  readonly 'date-timeNull'?: string | null;
  readonly bark: string;
  readonly color?: 'red' | 'green' | null;
  readonly size?: 'Big' | 'small';
  /**
   * @Format uuid
   */
  readonly uid?: string;
  /**
   * @Format uuid
   */
  readonly uidNull?: string | null;
}

export interface ExtendOne extends Dog {}

export interface ExtendTwo extends Cat, Dog {}

export interface ExtendTwoAndProperties extends Cat, Dog {
  /**
   * @Format money
   */
  readonly prices?: number;
}
