/**
 * This file was auto-generated by the program based on the back-end data structrue.
 * Do not make direct changes to the file.
 */

/**
 * @Description age query
 *
 * @Format base64
 */
export interface Age {
  readonly ag?: string;
}
