/**
 * This file was auto-generated by the program based on the back-end data structrue.
 * Do not make direct changes to the file.
 */

export interface BusinessGetPath {
  /**
   * @Description id in path
   *
   * @Deprecated False
   *
   * @AllowEmptyValue False
   *
   * @Explode True
   *
   * @AllowReserved True
   *
   * @SerializeFormat form
   */
  readonly id: number;
  readonly name: string;
}
