/**
 * This file was auto-generated by the program based on the back-end data structrue.
 * Do not make direct changes to the file.
 */

export interface BusinessGetEP {
  Request: {
    Query: BusinessGetQuery;
  };
  Responses: {
    /**
     * @Description success
     */
    200: {
      Content: null;
    };
  };
}

export interface BusinessGetQuery {
  readonly versionInfo?: {
    /**
     * @Format date-time
     */
    readonly 'Date-From': string;
    /**
     * @Format date-time
     */
    readonly 'Date-FromNull'?: string | null;
    readonly id: number;
    readonly idWithNull?: number | null;
    readonly isActive: boolean;
    readonly isActiveNull?: boolean | null;
    /**
     * @Format uuid
     */
    readonly uid: string;
    /**
     * @Format uuid
     */
    readonly uidNull?: string | null;
  } | null;
}
