/**
 * This file was auto-generated by the program based on the back-end data structrue.
 * Do not make direct changes to the file.
 */

export interface BusinessGetEP {
  Request: {
    Query: BusinessGetQuery;
  };
  Responses: {
    /**
     * @Description not found
     */
    200: {
      Content: {
        'application/json': {
          readonly int: number;
          readonly object?: Age;
          readonly string?: string;
        };
      };
    };
  };
}

export interface BusinessGetQuery {
  readonly address?: {
    readonly isActive: boolean;
  };
  readonly id: number;
}

export interface Age {
  readonly name?: string;
}
