/**
 * This file was auto-generated by the program based on the back-end data structrue.
 * Do not make direct changes to the file.
 */

import { Address, AddressResponse } from './data-schema';
import { NonNullAsRequired } from './helper';

export interface BusinessGetEP {
  Request: {
    Query: BusinessGetQuery;
  };
  Responses: {
    /**
     * @Description not found
     */
    200: {
      Content: {
        'application/html': AddressResponse;
        'application/json': AddressResponse;
        'application/stream+json': BusinessGet200ApplicationStreamJson;
        'application/xhtml+xml': BusinessGet200ApplicationXhtmlXml;
      };
    };
  };
}

export type BusinessGet200ApplicationStreamJson = NonNullAsRequired<{
  readonly id?: boolean;
  readonly name?: string;
}>;

export type BusinessGet200ApplicationXhtmlXml = NonNullAsRequired<{
  readonly id?: boolean;
  readonly name?: string;
}>;

export interface BusinessGetQuery {
  readonly id?: Address;
}
