/**
 * This file was auto-generated by the program based on the back-end data structrue.
 * Do not make direct changes to the file.
 */

import { NonNullAsRequired } from './helper';

export type AddressResponse = NonNullAsRequired<Address>;

export interface Address {
  readonly id?: boolean;
  readonly name?: string;
}
