/**
 * This file was auto-generated by the program based on the back-end data structrue.
 * Do not make direct changes to the file.
 */

import {
  BusinessGetCookie,
  BusinessGetHeader,
  BusinessGetPath,
  BusinessGetQuery
} from './data-schema';

/**
 * @Summary business get operation summary
 *
 * @Description business get operation
 */
export interface BusinessGetEP {
  Request: {
    Cookie: BusinessGetCookie;
    Header: BusinessGetHeader;
    Path: BusinessGetPath;
    Query: BusinessGetQuery;
  };
  Responses: {
    /**
     * @Description not found
     */
    200: {
      Content: null;
    };
  };
}
