/**
 * This file was auto-generated by the program based on the back-end data structure.
 * Do not make direct changes to the file.
 */

import { RefObject } from './data-schema';

export interface BusinessGetEP {
  Request: {
    Query: BusinessGetQuery;
  };
  Responses: {
    /**
     * @Description success
     */
    200: {
      Content: {
        'application/json': {
          readonly inline: {
            readonly age?: number;
            readonly name?: string;
          };
          readonly refObject?: RefObject;
        };
      };
    };
  };
}

export interface BusinessGetQuery {
  readonly req?: RefObject;
}
